#! /bin/bash

#   Add cryptsetup service files to runlevel/boot

/bin/cp /etc/init.d/{cryptdisks,cryptdisks-early} /etc/runlevels/boot || true

#   Add dmcrypt service files to runlevel/boot

rc-update add dmcrypt boot
rc-update add dmeventd boot
rc-update add device-mapper boot
rc-update add cryptmount boot

#   Update services list

rc-update -u
